### ISSUE TITLE
CSS for new logout button

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/care#4]
A new logout button is displayed in the "Your Data" header in OPC Pages, OPC Shop Grids and in the ```/shop/checkout``` page if OPC is enabled globally. 

This new button needs to be styled for care to not interrupt with the current form. 

Design:
- [x] Background should be white
- [x] NO round corners for the button
- [x] Should be a bit smaller than the yellow background of the Header
- [x] Float Right
- [x] Informe Care

<img width="1000" alt="bildschirmfoto 2017-02-22 um 14 29 52" src="https://cloud.githubusercontent.com/assets/6480630/23213502/74bd0996-f90b-11e6-8cc2-f25bb61b53f5.png">

<img width="707" alt="bildschirmfoto 2017-02-22 um 14 30 10" src="https://cloud.githubusercontent.com/assets/6480630/23213506/798aaae6-f90b-11e6-9648-187f492a4bde.png">

**Comment by winston6071** [comment]
#4

**Comment by winston6071** [comment]
#4 #5aa2a73d7600858680370727902ebfc3156248db
